/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuPaciente = new javax.swing.JMenuItem();
        menuMedico = new javax.swing.JMenuItem();
        menuAtendimento = new javax.swing.JMenuItem();
        menuExame = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/hospital imagem.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        menuPaciente.setText("Paciente");
        menuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPaciente);

        menuMedico.setText("Médico");
        menuMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMedicoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuMedico);

        menuAtendimento.setText("Atendimento");
        menuAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAtendimentoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuAtendimento);

        menuExame.setText("Exame");
        menuExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExameActionPerformed(evt);
            }
        });
        menuCadastro.add(menuExame);

        jMenuBar1.add(menuCadastro);

        menuAjuda.setText("Ajuda");

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Sistema de Cadastro\nVersão 1.0\nTodos os direitos reservados");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAtendimentoActionPerformed
        // TODO add your handling code here:
        FormAtendimento form = new FormAtendimento(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); //desabilita o x
        form.setLocationRelativeTo(null); //centraliza a janela
        form.setResizable(false);//retira o botão maximizar
        form.setVisible(true);//mostra janela
    }//GEN-LAST:event_menuAtendimentoActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMedicoActionPerformed
        // TODO add your handling code here:
        FormMedico form = new FormMedico(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); //desabilita o x
        form.setLocationRelativeTo(null); //centraliza a janela
        form.setResizable(false);//retira o botão maximizar
        form.setVisible(true);//mostra janela
    }//GEN-LAST:event_menuMedicoActionPerformed

    private void menuExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExameActionPerformed
        // TODO add your handling code here:
        FormExame form = new FormExame(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); //desabilita o x
        form.setLocationRelativeTo(null); //centraliza a janela
        form.setResizable(false);//retira o botão maximizar
        form.setVisible(true);//mostra janela
    }//GEN-LAST:event_menuExameActionPerformed

    private void menuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacienteActionPerformed
        // TODO add your handling code here:
        FormPaciente form = new FormPaciente(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); //desabilita o x
        form.setLocationRelativeTo(null); //centraliza a janela
        form.setResizable(false);//retira o botão maximizar
        form.setVisible(true);//mostra janela
    }//GEN-LAST:event_menuPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormPrincipal().setVisible(true);
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);//centraliza a tela
                form.setVisible(true);//mostra a janela
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAtendimento;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuExame;
    private javax.swing.JMenuItem menuMedico;
    private javax.swing.JMenuItem menuPaciente;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables

}